Feat/share url
ConcordUSA/engineering-training-01 pull request #68
Opened 2021-02-23 22:39 UTC by CooperDoten

2021-02-23 22:41 UTC, adamschnaare requested changes

2021-02-23 22:41 UTC, adamschnaare commented on packages/client/src/views/SimpleModal.tsx
> +      <h2 id="simple-modal-title">Text in a modal</h2>
What's the lorem ipsum in here for?

2021-02-24 15:01 UTC, CooperDoten commented on packages/client/src/views/SimpleModal.tsx
> +      <h2 id="simple-modal-title">Text in a modal</h2>
I just pushed a new PR that resolves this issue. Was just in progress last night.

2021-02-24 17:50 UTC, adamschnaare approved these changes

2021-02-24 17:50 UTC, merged